google_analytics_id: UA-84829010-3

repository: https://github.com/Y-Lab/Y-Lab

timezone: Asia/Shanghai

title: Y-Lab
description: Y-English Research and Development Laboratory
url: https://lab.y-english.org

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: Y-English
organization_url: https://y-english.org

contact: dev@y-english.org
github: https://github.com/Y-Lab

image: /img/logo/logo-dark.png
logo: /img/logo/logo-dark.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor